### ISSUE TITLE
How to install and use...😦

### ISSUE THREAD

**Issue by 1trapbox** [Freed-Wu/fzf-tab-source#10]
Check the installation documentation...but I still don't understand...
`.zshrc` configfile I have these
```
zinit light Aloxaf/fzf-tab
zinit light Freed-Wu/fzf-tab-source
source /home/user/.local/zinit/plugins/Freed-Wu---fzf-tab-source/sources/*.zsh
```
Then I deleted some of my settings. 
eg:
`zstyle ':fzf-tab:complete:cd:*' fzf-preview 'eza -1 --color=always $realpath'`
But I didn't feel any change.

[Preview gallery](https://github.com/Aloxaf/fzf-tab/wiki/Preview#preview-gallery)
**Note: if you don't want to spend time to write these configs by yourself, you can try [this zsh plugin](https://github.com/Freed-Wu/fzf-tab-source).**

what steps did I take wrong?
or, I understood it wrong, I still need to configure fzf-tab manually, right?

I'd appreciate a response. thanks🙏

**Comment by Freed-Wu** [comment]
My `~/.zshrc` is <https://github.com/Freed-Wu/Freed-Wu/blob/main/.zshrc#L241-L247>

Don't need to `source /home/user/.local/zinit/plugins/Freed-Wu---fzf-tab-source/sources/*.zsh`. They will be sourced automatically. Directly source them is incorrect. I think delete the incorrect line can make it work.

And make sure fzf have been installed.

**Comment by Freed-Wu** [comment]
I have added

> Don't source *.zsh! They will be sourced by *.plugin.zsh automatically.

to README.md. Thanks for your issue.

<https://github.com/Freed-Wu/fzf-tab-source#install>
