### ISSUE TITLE
Top level completions don't work

### ISSUE THREAD

**Issue by Magniquick** [Freed-Wu/fzf-tab-source#11]
Top level completions like this: <img width="1052" alt="Screenshot 2024-01-13 at 6 09 07 PM" src="https://github.com/Freed-Wu/fzf-tab-source/assets/67406856/09f51295-4895-4765-8f32-d0c6d5d93adb">
dont show a preview, while when it is a subcommand like this:
<img width="1052" alt="Screenshot 2024-01-13 at 6 08 23 PM" src="https://github.com/Freed-Wu/fzf-tab-source/assets/67406856/d116d6f7-32db-4c8f-a92c-5683b5c44ecb">
it works perfectly fine !

My lessfilter: [lessfilter.txt](https://github.com/Freed-Wu/fzf-tab-source/files/13927988/lessfilter.txt)

**Comment by Freed-Wu** [comment]
Works for me.

1. Can you report your plugin version? Just update it to latest.
2. Can you `rm ~/.lessfilter` then try again? Even if you don't have `.lessfilter`, `lesspipe` will use `ls` to view the directory by default.

**Comment by Magniquick** [comment]
It's on the latest version, just updated it today
The bug still occurs after removing the custom lessfilter
Note that I am on macos, tho I'm not sure how that could affect anything.

**Comment by Freed-Wu** [comment]
> Works for me.

![Screenshot from 2024-01-14 10-41-28](https://github.com/Freed-Wu/fzf-tab-source/assets/32936898/709fac3f-0a28-41d7-b571-5e22bc7d8b92)

Yes, I use GNU/Linux. It is weird that it cannot work for macOS.

Can you provide the result of `/<C-X>h`? In my machine, it is:

```sh
$ /
tags in context :completion::complete:-command-::
    commands executables builtins functions aliases suffix-aliases reserved-words jobs parameters parameters  (_command_names _autocd)
    commands                                                                                                  (_path_commands _command_names _autocd)
    globbed-files                                                                                             (_files _command_names _autocd)
    directories                                                                                               (_files _command_names _autocd)
    all-files                                                                                                 (_files _command_names _autocd)
    jobs                                                                                                      (_jobs _command_names _autocd)
    parameters                                                                                                (_parameters _command_names _autocd)
tags in context :completion::user-expand:::
    all-expansions expansions original  (_user_expand _ftb__main_complete -ftb-complete)
```

**Comment by Magniquick** [comment]
here you go:
```bash
tags in context :completion::complete:-command-::
    commands builtins functions aliases suffix-aliases reserved-words jobs parameters parameters  (_command_names _autocd)
    commands                                                                                      (_path_commands _command_names _autocd)
    jobs                                                                                          (_jobs _command_names _autocd)
    local-directories                                                                             (_cd _autocd)
```

**Comment by Freed-Wu** [comment]
> adding an echo test does nothing when it's not a subcommand, while it works otherwise.

Can you explain it in detail?

**Comment by Magniquick** [comment]
As in adding an echo test to the top of my lessfilter should have caused the preview to output test, no matter whatever it was detecting the mime type as.
however, it still shows no output - seems like it simply isnt rvrn run.

**Comment by Magniquick** [comment]
Fixed it !
Went through your .zshrc and copied all the zstyle configs related to completion
A small manual binary search through those yielded:
```zsh
zstyle ':completion:*:descriptions' format %d
```
This fixes it !
Could you please explain to me what exactly this does ?
Thanks a lot too !

**Comment by Freed-Wu** [comment]
<https://zsh.sourceforge.io/Doc/Release/Completion-System.html#Standard-Tags>:

> descriptions
>
>    used when looking up the value of the format style to generate descriptions for types of matches

It really be a bug. I'll fix it. Thanks for your reporting!

**Comment by Freed-Wu** [comment]
<https://github.com/Aloxaf/fzf-tab/wiki/Preview#group>:

> $group
> 
> This is the description of the group which the $word belongs to.
> 
> For example, --accessed belongs to group named [option], and README.md belongs to [filename].
> 
> README.md belongs to [filename] to completing exa, but belongs to [files] when completing ls.
> 
> NOTE: To use this variable, please make sure you have set zstyle ':completion:*:descriptions' format '[%d]'.

This plugin uses `$group` in some fzf-tab sources. So it is needed. I'll add this code to this plugin.

**Comment by Czy014** [comment]
> fzf-tab's $group will return group's description `[XXX]`, not real group name `XXX`. Maybe https://github.com/Aloxaf/fzf-tab can provide a new variable for it.

Since I am not familiar with the shell, I cannot fully understand what you mean. Is it a bug in fzf-tab? So I can only use the version you fixed in the project and cannot specify the format myself, right?

**Comment by Freed-Wu** [comment]
Oh, I means fzf-tab provide a variable $group which value is `[XXX]` when you set `[%d]` and `XXX` when you set `%d`. this project judge `$group` with `XXX`, so it cannot work. We have two solutions:

1. fzf-tab provide a `$group_name` which always be `XXX`, then we use it in this project.
2. We create a `$group_name` which value is `XXX` according to `$group` and `[%d]`. then we use it.
