### ISSUE TITLE
homebrew completions cannot work

### ISSUE THREAD

**Issue by Magniquick** [Freed-Wu/fzf-tab-source#13]
Right now, it seems like brew commands do not have a preview.
from the fzf-tab wiki, this does work:
```
zstyle ':fzf-tab:complete:brew-(install|uninstall|search|info):*-argument-rest' fzf-preview 'brew info $word'
```
maybe consider adding it ?

**Comment by Freed-Wu** [comment]
> Right now, it seems like brew commands do not have a preview.

It should be a bug. I'll take a look.

**Comment by Freed-Wu** [comment]
> zstyle ':fzf-tab:complete:brew-(install|uninstall|search|info):*-argument-rest' fzf-preview 'brew info $word'

`*-argument-rest` is right. Or precise `(cask|formula)-argument-rest`.

**Comment by Magniquick** [comment]
The uninstall command still has a problem - the rest of the commands do work.

**Comment by Magniquick** [comment]
seems like the ``*-argument-rest`` is required for a lot of stuff, including brew cat, brew uninstall, etc - ``(cask|formula)-argument-rest`` doesn't cut it out.

**Comment by Freed-Wu** [comment]
> The uninstall command still has a problem

You are right. It should be `(|installed_)(tap|cask|formula)-argument-rest`
