### ISSUE TITLE
I can't get it to work fully

### ISSUE THREAD

**Issue by halvabner** [Freed-Wu/fzf-tab-source#16]
Can you help me understand why it won't work?
### Problem
I only get previews for certain files like text files. For most others, like directories I get:
![image](https://github.com/Freed-Wu/fzf-tab-source/assets/130675714/5cc4c2a5-5317-4c11-b640-c1efd06c17b0)
![image](https://github.com/Freed-Wu/fzf-tab-source/assets/130675714/98303dab-ac7c-4c47-97f4-f6cee2b73b98)
Also for text files it uses `cat`, not `bat`
### Info
I tried installing from the [AUR](https://aur.archlinux.org/packages/fzf-tab-source) and also pulling from the repo directly.
These are the relevant lines in my `.zshrc`. I tried disabling many of them without success.
```
_fzf_compgen_path() {
  fd --hidden --follow --exclude ".git" . "$1"
}
# Use fd to generate the list for directory completion
_fzf_compgen_dir() {
  fd --type d --hidden --follow --exclude ".git" . "$1"
}
[ -f /usr/share/fzf/completion.zsh ] && . /usr/share/fzf/completion.zsh
[ -f /usr/share/fzf/key-bindings.zsh ] && . /usr/share/fzf/key-bindings.zsh
[ -f ~/.fzf-tab-source/fzf-tab-source.plugin.zsh ] && . ~/.fzf-tab-source/fzf-tab-source.plugin.zsh
[ -f ~/.fzf-tab/fzf-tab.plugin.zsh ] && . ~/.fzf-tab/fzf-tab.plugin.zsh
zstyle ':fzf-tab:*' fzf-bindings 'ctrl-space:toggle+down'
```
This is a relevant line in my `.zprofile`
```
export FZF_DEFAULT_OPTS="--bind=tab:down,shift-tab:up,ctrl-space:toggle+down"
```
I also tried removing it and rebooting.

**Comment by Freed-Wu** [comment]
Looks like #12?
