### ISSUE TITLE
Only enable selected plugins

### ISSUE THREAD

**Issue by sobolevn** [Freed-Wu/fzf-tab-source#20]
Hi! I only want to enable several plugins, not all of them.
Please, provide a way (similar to `plugins=()` in `.zshrc`) to do that :)

**Comment by Freed-Wu** [comment]
You can override some sources https://github.com/Freed-Wu/fzf-tab-source?tab=readme-ov-file#customize

Such as you want to disable completion of `dconf`:

![Screenshot from 2024-04-27 06-17-55](https://github.com/Freed-Wu/fzf-tab-source/assets/32936898/80c4a311-21e0-4c01-98e2-cfe3f4b39bbd)

Just add the following code to your `~/.zshrc` before you source this plugin:

```zsh
zstyle ':fzf-tab:sources' config-directory ~/.config/fzf-tab
```

copy the original source,

```sh
cp ~/.local/share/zinit/plugins/fzf-tab-source/sources/dconf.zsh ~/.config/fzf-tab
```

then edit its content to only level comment:

```
# :fzf-tab:complete:(\\|*/|)dconf(|-help):
```

Now it will be empty.

![Screenshot from 2024-04-27 06-18-09](https://github.com/Freed-Wu/fzf-tab-source/assets/32936898/8399d83b-fe74-4e9d-88b2-35f167baabe1)

**Comment by sobolevn** [comment]
Sorry, but this is not the solution. I want to disable lots of plugin, while keeping multiple others. Having a configuration instead of juggling source files would be much better.

But, this is your project. I respect your decision :)

**Comment by Freed-Wu** [comment]
If you want to disable all sources then only enable `git blame` and `git diff`,
you can try

```zsh
# .zshrc
zstyle ':fzf-tab:sources' config-directory ~/.config/fzf-tab
```

Then in your zsh:

```zsh
# Assume your plugin is here
cd ~/.local/share/zinit/plugins/fzf-tab-source/sources
cd -- *~(git-blame.zsh|git-diff.zsh) ~/.config/fzf-tab
# Install parallel
parallel sed -i '2,$d' ::: ~/.config/fzf-tab/*
```

No offense.
I just feel the requirement is too unpopular to add a new setting for it.
Now existing setting `config-directory` can cover it and provide more flexibility.
