### ISSUE TITLE
kill completion doesn't show all process

### ISSUE THREAD

**Issue by lmBored** [Freed-Wu/fzf-tab-source#22]
when I do
```kill -9 **<tab>```
it shows more processes than
```kill -9 <tab>```

<img width="1454" alt="image" src="https://github.com/user-attachments/assets/e0e54e5e-7209-492a-ae55-eac248f989cb">

I think this is causes because fzf-tab can't access all processes.

**Comment by Freed-Wu** [comment]
`**` complete all files of `$PWD` for me, not all process. Do you use any other zsh plugin to realize it?

**Comment by lmBored** [comment]
Oh just now, I've learned that `**` works the same for all commands. Initially I thought it work differently per commands (like different for `kill` and for `ls`...). Thank you for your help. fzf-tab-source works great!
