### ISSUE TITLE
add install instructions

### ISSUE THREAD

**Issue by m-fonseca** [Freed-Wu/fzf-tab-source#3]
Hello, 

I was trying to use this and the instructions don't actually say how to install this.  A line saying to source the `fzf-tab-source.plugin.zsh`  would be helpful.  (Maybe this would be automatically done with plugin managers, but I don't use any..?).

Thanks!

**Comment by Freed-Wu** [comment]
Thanks for your suggestion. I'll add it :heart:

**Comment by Freed-Wu** [comment]
See <https://github.com/Freed-Wu/fzf-tab-source#install>.
