### ISSUE TITLE
Do not spoil home directory

### ISSUE THREAD

**Issue by ragu-manjegowda** [Freed-Wu/fzf-tab-source#8]
Thanks for the amazing plugin.

Please do not create empty directories by default.

Empty file within directory under `$HOME/.gitmoji/` is created irrespective of whether program is installed or not.

May be you can just add a check to see if `gitmoji` is installed before [creating the directory](https://github.com/Freed-Wu/fzf-tab-source/blob/main/functions/main.zsh#L16)

**Comment by Freed-Wu** [comment]
I agree with you :+1:
