### ISSUE TITLE
get current width and height ? 

### ISSUE THREAD

**Issue by Magniquick** [Freed-Wu/fzf-tab-source#9]
Is it possible to get the current width and hight of the preview box ?

I am trying to make [timg](https://github.com/hzeller/timg) work with this but it requires the current width and height of the terminal.
tput and the env variables ($LINES etc) point to the actual terminal, while stty fails.

**Comment by Freed-Wu** [comment]
:cry: Sorry I use [chafa](https://github.com/hpjansson/chafa) and not familiar with [timg](https://github.com/hzeller/timg). <https://github.com/Freed-Wu/Freed-Wu/blob/dev/.lessfilter#L92>

you can ask <https://github.com/Aloxaf/fzf-tab> about how to get height and width.
or <https://github.com/hzeller/timg> about is it possible to not to require height and width.

**Comment by Magniquick** [comment]
> 😢 Sorry I use [chafa](https://github.com/hpjansson/chafa) and not familiar with [timg](https://github.com/hzeller/timg). https://github.com/Freed-Wu/Freed-Wu/blob/dev/.lessfilter#L92
> 
> you can ask https://github.com/Aloxaf/fzf-tab about how to get height and width. or https://github.com/hzeller/timg about is it possible to not to require height and width.

Fzf-tab seems to be quite dead at this moment.
Timg works after setting the height and width to a ridiculously large value, but if the image is longer than it is wider, it overflows the fzf box and the overflowed part stays there, even while previewing another file.
